services:

  postgres:
    image: postgres:17
    container_name: abs-commerce-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - abs-commerce-network

  api:
    image: absjrdev/abs-commerce-api:latest

    build:
      context: .

    container_name: abs-commerce-api

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    networks:
      - abs-commerce-network

volumes:
  postgres-data:

networks:
  abs-commerce-network: